hostname = www.theguardian.com, ddrk.me, *.theguardian.com
^https:?/\/www.theguardian.com.* url response-body <head> response-body <head><link rel="stylesheet" href="https://raw.githubusercontent.com/isinglever/Adguard/main/CSS/theguardian.css" type="text/css">

^https:?/\/ddrk.me.* url response-body <head> response-body <head><link rel="stylesheet" href="https://limbopro.com/CSS/ddrk.css" type="text/css"><script type="text/javascript"  src="https://raw.githubusercontent.com/isinglever/Adguard/main/JS/theguardian.js"></script>
