hostname = www.theguardian.com
^https:?/\/www.theguardian.com.* url response-body <head> response-body <head><link rel="stylesheet" href="https://raw.githubusercontent.com/isinglever/Adguard/main/CSS/theguardian.css" type="text/css">
