// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/response/config.proto (package youtube.response.config, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.response.config.Config
 */
export const Config = proto3.makeMessageType(
  "youtube.response.config.Config",
  () => [
    { no: 1, name: "response_context", kind: "message", T: ResponseContext },
  ],
);

/**
 * @generated from message youtube.response.config.ResponseContext
 */
export const ResponseContext = proto3.makeMessageType(
  "youtube.response.config.ResponseContext",
  () => [
    { no: 16, name: "globalConfigGroup", kind: "message", T: GlobalConfigGroup },
  ],
);

/**
 * @generated from message youtube.response.config.GlobalConfigGroup
 */
export const GlobalConfigGroup = proto3.makeMessageType(
  "youtube.response.config.GlobalConfigGroup",
  () => [
    { no: 6, name: "coldConfigGroup", kind: "message", T: ColdConfigGroup },
    { no: 7, name: "hotConfigGroup", kind: "message", T: HotConfigGroup },
    { no: 4, name: "hot_hash_data", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "cold_hash_data", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message youtube.response.config.ColdConfigGroup
 */
export const ColdConfigGroup = proto3.makeMessageType(
  "youtube.response.config.ColdConfigGroup",
  [],
);

/**
 * @generated from message youtube.response.config.HotConfigGroup
 */
export const HotConfigGroup = proto3.makeMessageType(
  "youtube.response.config.HotConfigGroup",
  () => [
    { no: 138536474, name: "mediaHotConfig", kind: "message", T: MediaHotConfig },
  ],
);

/**
 * @generated from message youtube.response.config.MediaHotConfig
 */
export const MediaHotConfig = proto3.makeMessageType(
  "youtube.response.config.MediaHotConfig",
  () => [
    { no: 146311580, name: "onesieHotConfig", kind: "message", T: OnesieHotConfig },
  ],
);

/**
 * @generated from message youtube.response.config.OnesieHotConfig
 */
export const OnesieHotConfig = proto3.makeMessageType(
  "youtube.response.config.OnesieHotConfig",
  () => [
    { no: 1, name: "clientKey", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "encryptKey", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 3, name: "keyExpiresInSeconds", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 30, name: "useHotConfigToCreateOnesieRequest", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

