// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/response/config.proto (package youtube.response.config, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.response.config.Config
 */
export declare class Config extends Message<Config> {
  /**
   * @generated from field: youtube.response.config.ResponseContext response_context = 1;
   */
  responseContext?: ResponseContext;

  constructor(data?: PartialMessage<Config>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.config.Config";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Config;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Config;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Config;

  static equals(a: Config | PlainMessage<Config> | undefined, b: Config | PlainMessage<Config> | undefined): boolean;
}

/**
 * @generated from message youtube.response.config.ResponseContext
 */
export declare class ResponseContext extends Message<ResponseContext> {
  /**
   * @generated from field: youtube.response.config.GlobalConfigGroup globalConfigGroup = 16;
   */
  globalConfigGroup?: GlobalConfigGroup;

  constructor(data?: PartialMessage<ResponseContext>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.config.ResponseContext";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResponseContext;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResponseContext;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResponseContext;

  static equals(a: ResponseContext | PlainMessage<ResponseContext> | undefined, b: ResponseContext | PlainMessage<ResponseContext> | undefined): boolean;
}

/**
 * @generated from message youtube.response.config.GlobalConfigGroup
 */
export declare class GlobalConfigGroup extends Message<GlobalConfigGroup> {
  /**
   * @generated from field: youtube.response.config.ColdConfigGroup coldConfigGroup = 6;
   */
  coldConfigGroup?: ColdConfigGroup;

  /**
   * @generated from field: youtube.response.config.HotConfigGroup hotConfigGroup = 7;
   */
  hotConfigGroup?: HotConfigGroup;

  /**
   * @generated from field: optional string hot_hash_data = 4;
   */
  hotHashData?: string;

  /**
   * @generated from field: optional string cold_hash_data = 5;
   */
  coldHashData?: string;

  constructor(data?: PartialMessage<GlobalConfigGroup>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.config.GlobalConfigGroup";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GlobalConfigGroup;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GlobalConfigGroup;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GlobalConfigGroup;

  static equals(a: GlobalConfigGroup | PlainMessage<GlobalConfigGroup> | undefined, b: GlobalConfigGroup | PlainMessage<GlobalConfigGroup> | undefined): boolean;
}

/**
 * @generated from message youtube.response.config.ColdConfigGroup
 */
export declare class ColdConfigGroup extends Message<ColdConfigGroup> {
  constructor(data?: PartialMessage<ColdConfigGroup>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.config.ColdConfigGroup";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ColdConfigGroup;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ColdConfigGroup;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ColdConfigGroup;

  static equals(a: ColdConfigGroup | PlainMessage<ColdConfigGroup> | undefined, b: ColdConfigGroup | PlainMessage<ColdConfigGroup> | undefined): boolean;
}

/**
 * @generated from message youtube.response.config.HotConfigGroup
 */
export declare class HotConfigGroup extends Message<HotConfigGroup> {
  /**
   * @generated from field: youtube.response.config.MediaHotConfig mediaHotConfig = 138536474;
   */
  mediaHotConfig?: MediaHotConfig;

  constructor(data?: PartialMessage<HotConfigGroup>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.config.HotConfigGroup";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HotConfigGroup;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HotConfigGroup;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HotConfigGroup;

  static equals(a: HotConfigGroup | PlainMessage<HotConfigGroup> | undefined, b: HotConfigGroup | PlainMessage<HotConfigGroup> | undefined): boolean;
}

/**
 * @generated from message youtube.response.config.MediaHotConfig
 */
export declare class MediaHotConfig extends Message<MediaHotConfig> {
  /**
   * @generated from field: youtube.response.config.OnesieHotConfig onesieHotConfig = 146311580;
   */
  onesieHotConfig?: OnesieHotConfig;

  constructor(data?: PartialMessage<MediaHotConfig>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.config.MediaHotConfig";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MediaHotConfig;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MediaHotConfig;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MediaHotConfig;

  static equals(a: MediaHotConfig | PlainMessage<MediaHotConfig> | undefined, b: MediaHotConfig | PlainMessage<MediaHotConfig> | undefined): boolean;
}

/**
 * @generated from message youtube.response.config.OnesieHotConfig
 */
export declare class OnesieHotConfig extends Message<OnesieHotConfig> {
  /**
   * @generated from field: bytes clientKey = 1;
   */
  clientKey: Uint8Array;

  /**
   * @generated from field: bytes encryptKey = 2;
   */
  encryptKey: Uint8Array;

  /**
   * @generated from field: int64 keyExpiresInSeconds = 3;
   */
  keyExpiresInSeconds: bigint;

  /**
   * @generated from field: bool useHotConfigToCreateOnesieRequest = 30;
   */
  useHotConfigToCreateOnesieRequest: boolean;

  constructor(data?: PartialMessage<OnesieHotConfig>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.config.OnesieHotConfig";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OnesieHotConfig;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OnesieHotConfig;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OnesieHotConfig;

  static equals(a: OnesieHotConfig | PlainMessage<OnesieHotConfig> | undefined, b: OnesieHotConfig | PlainMessage<OnesieHotConfig> | undefined): boolean;
}

