hostname = calm.com, api.busuu.com, dida365.com, ticktick.com, mobile-api.adguard.com

#calm 5.31.1
^https:\/\/api\.calm\.com\/me$ url script-response-body https://raw.githubusercontent.com/isinglever/Adguard/main/JS/calm.js

#busuu 24.19.0
^https:\/\/api\.busuu\.com\/users\/me* url script-response-body https://raw.githubusercontent.com/isinglever/Adguard/main/JS/busuu.js

#adguard 4.3.1
^https:\/\/mobile-api\.adguard\.com\/api\/1\.0\/ios_validate_receipt$ url script-response-body https://raw.githubusercontent.com/isinglever/Adguard/main/JS/adguard.js

# ticktick 6.1.81
^https:\/\/(ticktick|dida365)\.com\/api\/v2\/user\/status url script-response-body https://raw.githubusercontent.com/isinglever/Adguard/main/JS/ticktick.js
