hostname = calm.com, api.busuu.com, 

#calm 5.31.1
^https:\/\/api\.calm\.com\/me$ url script-response-body https://raw.githubusercontent.com/isinglever/Adguard/main/JS/calm.js

#busuu 24.19.0
^https:\/\/api\.busuu\.com\/users\/me* url script-response-body https://raw.githubusercontent.com/isinglever/Adguard/main/JS/busuu.js

