hostname = www.getpocket.com, ddrk.me, *.getpocket.com
^https:?/\/getpocket.com.* url response-body <head> response-body <head><link rel="apple-touch-icon-precomposed" sizes="57x57" href="https://static.zhihu.com/heifetz/assets/apple-touch-icon-152.a53ae37b.png">
