hostname = www.ptwxz.com, ddrk.me, *.getpocket.com
^https:?/\/www.ptwxz.com.* url response-body <head> response-body <head><link rel="apple-touch-icon" href="https://static.zhihu.com/heifetz/assets/apple-touch-icon-152.a53ae37b.png">
