#!name=Cake Crack
#!desc=Enjoy!

[MITM]
hostname = %APPEND% api.mycake.me, api.cakeapp.me

[Script]
cake_start = type=http-response, pattern=^https:\/\/api\.mycake\.me\/app\/start$, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/isinglever/adguard/main/js/cake/cake_start.js, timeout=60, script-update-interval=0
cake_sub_1 = type=http-response, pattern=^https:\/\/api.mycake.me\/v2\/main\/subscription\/channel.+, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/isinglever/adguard/main/js/cake/cake_sub.js, timeout=60, script-update-interval=0
cake_sub_2 = type=http-response, pattern=^https:\/\/api\.cakeapp\.me\/gw\/subscription.+, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/isinglever/adguard/main/js/cake/cake_sub.js, timeout=60, script-update-interval=0
cake_sum_1 = type=http-response, pattern=^https:\/\/api\.mycake\.me\/main\/learning\/summary.+, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/isinglever/adguard/main/js/cake/cake_sum.js, timeout=60, script-update-interval=0
cake_sum_2 = type=http-response, pattern=^https:\/\/api\.mycake\.me\/user\/learning\/log\/v2$, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/isinglever/adguard/main/js/cake/cake_sum.js, timeout=60, script-update-interval=0