#!name=Reddit 英文翻译与去广告
#!desc=开启 Reddit App 英文翻译，支持 Show Original，移除首页及评论广告，并隐藏底部 Games 标签
#!category=Self

[MITM]
hostname = %APPEND% gql.reddit.com, gql-fed.reddit.com

[Script]
reddit_trans = type=http-request,pattern=^https?:\/\/gql\.reddit\.com\/(?:\?.*)?$,requires-body=0,max-size=0,script-path=https://raw.githubusercontent.com/isinglever/adguard/main/js/reddit_request_en.js?v=20260823-1,timeout=60,script-update-interval=0
reddit_ads_request = type=http-request,pattern=^https?:\/\/gql-fed\.reddit\.com\/(?:\?.*)?$,requires-body=1,max-size=0,binary-body-mode=0,script-path=https://raw.githubusercontent.com/isinglever/adguard/main/js/reddit_request_en.js?v=20260823-1,timeout=60,script-update-interval=0
reddit_content_response = type=http-response,pattern=^https?:\/\/gql-fed\.reddit\.com\/(?:\?.*)?$,requires-body=1,max-size=0,binary-body-mode=0,script-path=https://raw.githubusercontent.com/isinglever/adguard/main/js/reddit_response.js?v=20260823-1,timeout=60,script-update-interval=0
