#!name=RevenueCat Crack
#!desc=Rewrite RevenueCat requests and responses to unlock entitlements.
#!category=Self

[Script]
revenuecat_header = type=http-request, pattern=^https:\/\/api\.(revenuecat|rc-backup)\.com\/.+\/(receipts|subscribers).*, requires-body=0, max-size=0, script-path=https://raw.githubusercontent.com/isinglever/adguard/main/js/revenueHeader.js, timeout=60, script-update-interval=0
revenuecat_body = type=http-response, pattern=^https:\/\/api\.(revenuecat|rc-backup)\.com\/.+\/(receipts$|subscribers\/[^/]+$), requires-body=1, max-size=0, script-path=https://raw.githubusercontent.com/isinglever/adguard/main/js/revenue.js, timeout=60, script-update-interval=0

[MITM]
hostname = %APPEND% api.revenuecat.com, api.rc-backup.com
