// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/request/onesieRequest.proto (package youtube.request.onesieRequestProto, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.request.onesieRequestProto.OnesieRequestProto
 */
export declare class OnesieRequestProto extends Message<OnesieRequestProto> {
  /**
   * @generated from field: repeated string urls = 1;
   */
  urls: string[];

  /**
   * @generated from field: youtube.request.onesieRequestProto.EncryptedInnertubeRequest innertube_request = 3;
   */
  innertubeRequest?: EncryptedInnertubeRequest;

  /**
   * @generated from field: bytes onesie_ustreamer_config = 4;
   */
  onesieUstreamerConfig: Uint8Array;

  /**
   * @generated from field: int32 max_vp9_height = 5;
   */
  maxVp9Height: number;

  /**
   * @generated from field: int32 client_display_height = 6;
   */
  clientDisplayHeight: number;

  constructor(data?: PartialMessage<OnesieRequestProto>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.request.onesieRequestProto.OnesieRequestProto";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OnesieRequestProto;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OnesieRequestProto;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OnesieRequestProto;

  static equals(a: OnesieRequestProto | PlainMessage<OnesieRequestProto> | undefined, b: OnesieRequestProto | PlainMessage<OnesieRequestProto> | undefined): boolean;
}

/**
 * @generated from message youtube.request.onesieRequestProto.EncryptedInnertubeRequest
 */
export declare class EncryptedInnertubeRequest extends Message<EncryptedInnertubeRequest> {
  /**
   * @generated from field: bytes encrypted_onesie_innertube_request = 2;
   */
  encryptedOnesieInnertubeRequest: Uint8Array;

  /**
   * @generated from field: bytes encrypted_client_key = 5;
   */
  encryptedClientKey: Uint8Array;

  /**
   * @generated from field: bytes iv = 6;
   */
  iv: Uint8Array;

  /**
   * @generated from field: bytes hmac = 7;
   */
  hmac: Uint8Array;

  /**
   * @generated from field: bool enable_compression = 8;
   */
  enableCompression: boolean;

  /**
   * @generated from field: string reverse_proxy_config = 9;
   */
  reverseProxyConfig: string;

  constructor(data?: PartialMessage<EncryptedInnertubeRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.request.onesieRequestProto.EncryptedInnertubeRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EncryptedInnertubeRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EncryptedInnertubeRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EncryptedInnertubeRequest;

  static equals(a: EncryptedInnertubeRequest | PlainMessage<EncryptedInnertubeRequest> | undefined, b: EncryptedInnertubeRequest | PlainMessage<EncryptedInnertubeRequest> | undefined): boolean;
}

