// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/request/onesieRequest.proto (package youtube.request.onesieRequestProto, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.request.onesieRequestProto.OnesieRequestProto
 */
export const OnesieRequestProto = proto3.makeMessageType(
  "youtube.request.onesieRequestProto.OnesieRequestProto",
  () => [
    { no: 1, name: "urls", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "innertube_request", kind: "message", T: EncryptedInnertubeRequest },
    { no: 4, name: "onesie_ustreamer_config", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "max_vp9_height", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "client_display_height", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message youtube.request.onesieRequestProto.EncryptedInnertubeRequest
 */
export const EncryptedInnertubeRequest = proto3.makeMessageType(
  "youtube.request.onesieRequestProto.EncryptedInnertubeRequest",
  () => [
    { no: 2, name: "encrypted_onesie_innertube_request", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "encrypted_client_key", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 6, name: "iv", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 7, name: "hmac", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 8, name: "enable_compression", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "reverse_proxy_config", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

