hostname = zfbjkt.scdsjzx.cn

^https?:\/\/zfbjkt\.scdsjzx\.cn\/papi\/t\/tpgethsjcfromsichuan url script-response-body https://raw.githubusercontent.com/isinglever/Adguard/main/JS/PCR_Test.js
^https?:\/\/zfbjkt\.scdsjzx\.cn\/papi\/t\/tpquerypasscoderemindstatus url script-response-body 
