// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/ump/encrypted.proto (package youtube.ump.encrypted, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum youtube.ump.encrypted.CompressionAlgorithm
 */
export const CompressionAlgorithm = proto3.makeEnum(
  "youtube.ump.encrypted.CompressionAlgorithm",
  [
    {no: 0, name: "NONE"},
    {no: 1, name: "GZIP"},
    {no: 2, name: "BROTLI"},
  ],
);

/**
 * @generated from message youtube.ump.encrypted.EncryptedInnertubeResponsePart
 */
export const EncryptedInnertubeResponsePart = proto3.makeMessageType(
  "youtube.ump.encrypted.EncryptedInnertubeResponsePart",
  () => [
    { no: 1, name: "encryptedContent", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "hmac", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 3, name: "iv", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 4, name: "compressionAlgorithm", kind: "enum", T: proto3.getEnumType(CompressionAlgorithm) },
  ],
);

