// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/ump/mediaHeader.proto (package youtube.ump.mediaHeader, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum youtube.ump.mediaHeader.CompressionAlgorithm
 */
export const CompressionAlgorithm = proto3.makeEnum(
  "youtube.ump.mediaHeader.CompressionAlgorithm",
  [
    {no: 0, name: "NONE"},
    {no: 1, name: "NONE_1"},
    {no: 2, name: "GZIP"},
  ],
);

/**
 * @generated from message youtube.ump.mediaHeader.MediaHeader
 */
export const MediaHeader = proto3.makeMessageType(
  "youtube.ump.mediaHeader.MediaHeader",
  () => [
    { no: 1, name: "headerId", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "videoId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "iTag", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "lastModified", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "xTags", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "startRange", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "compressionAlgorithm", kind: "enum", T: proto3.getEnumType(CompressionAlgorithm) },
    { no: 8, name: "isInitSegment", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "sequenceNumber", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 13, name: "formatId", kind: "message", T: FormatId },
    { no: 14, name: "length", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 15, name: "timeRange", kind: "message", T: TimeRange },
  ],
);

/**
 * @generated from message youtube.ump.mediaHeader.TimeRange
 */
export const TimeRange = proto3.makeMessageType(
  "youtube.ump.mediaHeader.TimeRange",
  () => [
    { no: 1, name: "start_ticks", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "duration_ticks", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "timescale", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message youtube.ump.mediaHeader.FormatId
 */
export const FormatId = proto3.makeMessageType(
  "youtube.ump.mediaHeader.FormatId",
  () => [
    { no: 1, name: "iTag", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "lastModified", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "xTags", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

