// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/ump/onesieInnertubeResponse.proto (package youtube.ump.encrypted, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Content } from "../response/watch_pb.js";

/**
 * @generated from message youtube.ump.encrypted.OnesieInnertubeResponse
 */
export const OnesieInnertubeResponse = proto3.makeMessageType(
  "youtube.ump.encrypted.OnesieInnertubeResponse",
  () => [
    { no: 4, name: "contents", kind: "message", T: Content, repeated: true },
  ],
);

