// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/ump/onesieInnertubeResponse.proto (package youtube.ump.encrypted, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Content } from "../response/watch_pb.js";

/**
 * @generated from message youtube.ump.encrypted.OnesieInnertubeResponse
 */
export declare class OnesieInnertubeResponse extends Message<OnesieInnertubeResponse> {
  /**
   * @generated from field: repeated youtube.response.watch.Content contents = 4;
   */
  contents: Content[];

  constructor(data?: PartialMessage<OnesieInnertubeResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.ump.encrypted.OnesieInnertubeResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OnesieInnertubeResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OnesieInnertubeResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OnesieInnertubeResponse;

  static equals(a: OnesieInnertubeResponse | PlainMessage<OnesieInnertubeResponse> | undefined, b: OnesieInnertubeResponse | PlainMessage<OnesieInnertubeResponse> | undefined): boolean;
}

