// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/ump/onesieHeader.proto (package youtube.ump.onesieHeader, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.ump.onesieHeader.OnesieHeader
 */
export declare class OnesieHeader extends Message<OnesieHeader> {
  /**
   *  string videoId = 2;
   *  string iTag = 3;
   *  uint64 lastModified = 5;
   *  int64 expectedMediaSizeBytes = 7;
   *  repeated string restrictedFormats = 11;
   *  string xTags = 15;
   *
   * @generated from field: int32 type = 1;
   */
  type: number;

  constructor(data?: PartialMessage<OnesieHeader>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.ump.onesieHeader.OnesieHeader";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OnesieHeader;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OnesieHeader;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OnesieHeader;

  static equals(a: OnesieHeader | PlainMessage<OnesieHeader> | undefined, b: OnesieHeader | PlainMessage<OnesieHeader> | undefined): boolean;
}

