// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/ump/onesieHeader.proto (package youtube.ump.onesieHeader, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.ump.onesieHeader.OnesieHeader
 */
export const OnesieHeader = proto3.makeMessageType(
  "youtube.ump.onesieHeader.OnesieHeader",
  () => [
    { no: 1, name: "type", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

