// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/ump/playStartPolicy.proto (package youtube.ump.playbackStartPolicy, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.ump.playbackStartPolicy.PlaybackStartPolicy
 */
export declare class PlaybackStartPolicy extends Message<PlaybackStartPolicy> {
  /**
   * @generated from field: repeated youtube.ump.playbackStartPolicy.MinReadAheadPolicy startMinReadAheadPolicy = 1;
   */
  startMinReadAheadPolicy: MinReadAheadPolicy[];

  /**
   * @generated from field: repeated youtube.ump.playbackStartPolicy.MinReadAheadPolicy resumeMinReadAheadPolicy = 2;
   */
  resumeMinReadAheadPolicy: MinReadAheadPolicy[];

  /**
   * @generated from field: string videoId = 3;
   */
  videoId: string;

  /**
   * @generated from field: int32 startTimeoutMs = 4;
   */
  startTimeoutMs: number;

  /**
   * @generated from field: int32 resumeTimeoutMs = 5;
   */
  resumeTimeoutMs: number;

  constructor(data?: PartialMessage<PlaybackStartPolicy>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.ump.playbackStartPolicy.PlaybackStartPolicy";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlaybackStartPolicy;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlaybackStartPolicy;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlaybackStartPolicy;

  static equals(a: PlaybackStartPolicy | PlainMessage<PlaybackStartPolicy> | undefined, b: PlaybackStartPolicy | PlainMessage<PlaybackStartPolicy> | undefined): boolean;
}

/**
 * @generated from message youtube.ump.playbackStartPolicy.MinReadAheadPolicy
 */
export declare class MinReadAheadPolicy extends Message<MinReadAheadPolicy> {
  /**
   * @generated from field: int64 minBandwidthBytesPerSec = 1;
   */
  minBandwidthBytesPerSec: bigint;

  /**
   * @generated from field: int32 minReadAheadMs = 2;
   */
  minReadAheadMs: number;

  constructor(data?: PartialMessage<MinReadAheadPolicy>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.ump.playbackStartPolicy.MinReadAheadPolicy";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MinReadAheadPolicy;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MinReadAheadPolicy;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MinReadAheadPolicy;

  static equals(a: MinReadAheadPolicy | PlainMessage<MinReadAheadPolicy> | undefined, b: MinReadAheadPolicy | PlainMessage<MinReadAheadPolicy> | undefined): boolean;
}

