// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/ump/playStartPolicy.proto (package youtube.ump.playbackStartPolicy, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.ump.playbackStartPolicy.PlaybackStartPolicy
 */
export const PlaybackStartPolicy = proto3.makeMessageType(
  "youtube.ump.playbackStartPolicy.PlaybackStartPolicy",
  () => [
    { no: 1, name: "startMinReadAheadPolicy", kind: "message", T: MinReadAheadPolicy, repeated: true },
    { no: 2, name: "resumeMinReadAheadPolicy", kind: "message", T: MinReadAheadPolicy, repeated: true },
    { no: 3, name: "videoId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "startTimeoutMs", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "resumeTimeoutMs", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message youtube.ump.playbackStartPolicy.MinReadAheadPolicy
 */
export const MinReadAheadPolicy = proto3.makeMessageType(
  "youtube.ump.playbackStartPolicy.MinReadAheadPolicy",
  () => [
    { no: 1, name: "minBandwidthBytesPerSec", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "minReadAheadMs", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

